/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AudioPlayer {
        "playerTitle": string;
        "src": string;
    }
}
declare global {
    interface HTMLAudioPlayerElement extends Components.AudioPlayer, HTMLStencilElement {
    }
    var HTMLAudioPlayerElement: {
        prototype: HTMLAudioPlayerElement;
        new (): HTMLAudioPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "audio-player": HTMLAudioPlayerElement;
    }
}
declare namespace LocalJSX {
    interface AudioPlayer {
        "playerTitle"?: string;
        "src"?: string;
    }
    interface IntrinsicElements {
        "audio-player": AudioPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "audio-player": LocalJSX.AudioPlayer & JSXBase.HTMLAttributes<HTMLAudioPlayerElement>;
        }
    }
}
